[project]
name = "mcp-asnlookup-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cymruwhois>=1.6",
    "mcp[cli]>=1.6.0",
]
