[project]
name = "irtoolshed-mcp-server"
version = "0.1.0"
description = "MCP Server providing tools for network incident response"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cymruwhois>=1.6",
    "mcp[cli]>=1.6.0",
]
